### ISSUE TITLE
Installing the Plugin on Windows

### ISSUE THREAD

**Issue by lovetox** [kalkin/gajim-omemo#12]
Hi, i cant get the Plugin to work.
1. If i download the Plugin from Gajims Pluginmanager, it downloads it puts it in my Plugin Directory, but i cant see it in Gajim under "Plugins", so i cant activate it or even know if its working. Iam using the newest Gajim version, do i have to use the older one (0.16.4) like in the readme described?
2. i have python 2.7.10 installed.
   if i try "pip install nxmpp" there is the error: Could not find a version that satisfies the requirement nxmpp; No matching distribution found for nxmpp

if i try "pip install python-axolotl" there is this error:

C:\Users\Philipp>pip2 install python-axolotl
Collecting python-axolotl
  Using cached python-axolotl-0.1.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): protobuf<3.0.0-alpha-2
,>=2.6 in c:\python27\lib\site-packages (from python-axolotl)
Requirement already satisfied (use --upgrade to upgrade): pycrypto in c:\python2
7\lib\site-packages (from python-axolotl)
Collecting python-axolotl-curve25519 (from python-axolotl)
  Using cached python-axolotl-curve25519-0.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages (from protobuf<3.0.0-alpha-2,>=2.6->python-axolotl)
Installing collected packages: python-axolotl-curve25519, python-axolotl
  Running setup.py install for python-axolotl-curve25519
    Complete output from command C:\Python27\python.exe -c "import setuptools, t
okenize;**file**='c:\users\philipp\appdata\local\temp\pip-build-fn5oko\py
thon-axolotl-curve25519\setup.py';exec(compile(getattr(tokenize, 'open', open)(
**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\
users\philipp\appdata\local\temp\pip-iezm7t-record\install-record.txt --single-v
ersion-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'axolotl_curve25519' extension
    creating build
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\curve
    creating build\temp.win32-2.7\Release\curve\ed25519
    creating build\temp.win32-2.7\Release\curve\ed25519\additions
    creating build\temp.win32-2.7\Release\curve\ed25519\nacl_sha512
    C:\Users\Philipp\AppData\Local\Programs\Common\Microsoft\Visual C++ for Pyth
on\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Icurve/ed25519/nacl_i
ncludes -Icurve/ed25519/additions -Icurve/ed25519 -IC:\Python27\include -IC:\Pyt
hon27\PC /Tccurve25519module.c /Fobuild\temp.win32-2.7\Release\curve25519module.
obj
    curve25519module.c
    curve25519module.c(76) : error C2143: syntax error : missing ';' before 'typ
e'
    curve25519module.c(78) : error C2065: 'result' : undeclared identifier
    curve25519module.c(82) : error C2143: syntax error : missing '{' before '*'
    curve25519module.c(100) : warning C4133: 'return' : incompatible types - fro
m 'PyObject *' to 'int *'
    curve25519module.c(146) : warning C4133: 'initializing' : incompatible types
- from 'int *(__cdecl *)(PyObject *,PyObject *)' to 'PyCFunction'
  error: command 'C:\Users\Philipp\AppData\Local\Programs\Common\Micros
  oft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2
  ---
  
  Command "C:\Python27\python.exe -c "import setuptools, tokenize;**file**='c:\us
  ers\philipp\appdata\local\temp\pip-build-fn5oko\python-axolotl-curve25519\
  \setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace
  ('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\philipp\appdata\lo
  cal\temp\pip-iezm7t-record\install-record.txt --single-version-externally-manage
  d --compile" failed with error code 1 in c:\users\philipp\appdata\local\temp\pip
  -build-fn5oko\python-axolotl-curve25519

hope you can help me to get this running.

**Comment by lovetox** [comment]
i was able to install "nbxmpp" now. is this "nxmpp" maybe wrong in the readme?

**Comment by lovetox** [comment]
i made it with xubuntu for now. would be great if someone could tell me whats the problem on windows 7

**Comment by kalkin** [comment]
@lovetox Thank you. Of course it should be `nbxmpp`. I fixed the README accordingly.

About the windows situation. I must admit that my knowledge about python deployment on Windows is _not_ existing. I'm also lacking any testing hardware/license for Windows.

You could try to upgrade `pycrypto` and `protobuf` and see if you can install python-axolotl.
`pip install --upgrade protobuf pycrypto python-axolotl`

There are some [notes](https://trac.gajim.org/wiki/Win32Env) in the Gajim Wiki perhaps they can help you.

**Comment by kalkin** [comment]
Any help for porting and running `gajim-omemo` on Windows would be appreciated!

**Comment by lovetox** [comment]
i could build all dependencies on windows 7 x64 with python 2.7.9 (32 bit version)

2.7.10 doesnt work for some reason.

but plugin is still not showing up.

questions is though, where does the windows version of gajim look for those dependency files .. i hope in the python directory, but could also be that they have to be copied somewhere else :)

any idea how i could get a error log like in linux, where i could probably see why it doesnt load?

**Comment by kalkin** [comment]
> questions is though, where does the windows version of Gajim look for those dependency files .. i hope in the python directory, but could also be that they have to be copied somewhere else :)

It is python / pip responsibilities to install the dependencies in to the right directory. You just have to make sure that you use exactly the same python for Gajim, which you used to install your dependencies. There could be in issue if you have multiple different python versions installed.

> any idea how i could get a error log like in Linux, where i could probably see why it doesnt load?

You can use the `launch.bat` which i assume does the same as `launch.sh`

**Comment by kalkin** [comment]
Any progress?

**Comment by lovetox** [comment]
no, i was just installing the exe from the gajim site.

if i try it like in your link, with cloning the rep, i cant get it even started with launch.bat
i am now mostly on linux anyway, so i give up for now

**Comment by lovetox** [comment]
i made it after 6 hours of work.

on Windows Gajim takes all its dependencies from a file called library.zip in the _bin_ folder of Gajim or out of the plugin folder.

so if you want that the plugin works out of the box after downloading it in the pluginmanager of Gajim, i think there is no way around providing all the dependencies with the plugin. would be great if you could do this as soon as possible, right now its not easy to get it running under windows.

dependencies are:

python-axolotl
axolotl_curve25519
google protobuf <3.0.0 alpha 1

and a file called

pkg_resources.py

which is in the standard python library, but not provided in the library.zip from Gajim.

for now the only way to get it working is

installing python 2.7.9
follow these instructions to build python-axolotl
https://github.com/tgalal/python-axolotl

then finding these files under PYTHONPATH\Lib\site-packages (also search for pkg_resources.py)

copy the following folders&files into the library.zip which is in the _bin_ folder in your main Gajim install Directory

axolotl
google
pkg_resources.py
axolotl_curve25519.pyd

then it should work.

what would also be great, to find the errors more easily in the future, some exception catching for all the dependencies.

as it is right now, if a module can not be imported, Gajim just ignores that package, without any error Message. Then the Plugin just doesnt show up. Even in the Debug logs is no error Message, at least i didnt find it.

**Comment by lovetox** [comment]
also in my journey to get this working i found this, probably an error, at least my python console didnt let me over it

in state.py

```
from axolotl.invalidversionexception import (InvalidVersionException,
                                             NoSessionException)
```

NoSessionException is in nosessionexception.py

**Comment by lovetox** [comment]
ok with plugin is working i meant, i see all the buttons

though if i click "Get Device Keys" this happens

```
Traceback (most recent call last):
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\ui.py", line 51, in on_click
    self.plugin.query_prekey(self.contact)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 246, in query_prekey
    self.fetch_device_bundle_information(state, to_jid, device_id)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 267, in fetch_device_bundle_information
    iq = BundleInformationQuery(jid, device_id)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 92, in __init__
    pubsub = PubsubNode(items)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 51, in __init__
    assert data is Node
AssertionError
```

but this is maybe unrelated to the installing of the plugin.

**Comment by kalkin** [comment]
@lovetox Thank you for your great research work! 

I have created a wiki page: [Compiling dependencies for Windows](https://github.com/kalkin/gajim-omemo/wiki/Compiling-dependencies-for-Windows). Could you glance over it and perhaps add missing bits, so we have a manual how to do this?

> installing python 2.7.9

Did you use 32bit or 64 bit? In general: 32bit vs 64bit. Do we deliver 32bit for all, or do we deliver both, or just 64? What is the rule on Windows for that?

> follow these instructions to build python-axolotl
> Exactly which version of zlib for Windows did you [install](http://www.winimage.com/zLibDll/)? 
> 
> copy the following folders&files into the library.zip which is in the bin folder in your main Gajim install Directory

Where do I put it in the `plugin/gajim-omemo` directory, have you tried that?

> what would also be great, to find the errors more easily in the future, some exception catching for all the dependencies.

Add another `-l plugin_system=DEBUG` (without `.omemo`) this will output all the debug output of the plugin system

> though if i click "Get Device Keys" this happens

Nice to see that my assert code is working :grinning: . This probably means that you getting strange XML. Could you please reproduce this error and copy paste the XML you receive (Actions -> Advance -> Show XML Console )?

**Comment by lovetox** [comment]
ok i will go over that wiki over the next week

> Where do I put it in the plugin/gajim-omemo directory, have you tried that?

i have to take that back, a windows user cant simply put it in the plugin folder of omemo. cause thats not a standard path where the dependencies are assumed. if you want to provide it there, like you do with the `store` folder you have to change all the paths in the `py` files. cause many axolotl files import with kind of absolut paths, like `from axolotl.ecc import blbabla` but this would not search the module in the plugin directory. so you would have to alter all the files to relative paths.

but im know nothing about python, maybe there is another way to import these files.

i found a another place where it works, you can put the files into the `bin` folder of Gajim, or the `library.zip` but the first choice is the more easy one of course.

why all regular python paths where you would find normal dependencies are ignored i dont know, must have to do with the way gajim is made on windows, cause its standalone, you dont need python to run it.

> Did you use 32bit or 64 bit? In general: 32bit vs 64bit. Do we deliver 32bit for all, or do we deliver both, or just 64? What is the rule on Windows for that?

i dont know enough about how that works to make that decision.

i installed everything in 32bit cause i read that some python versions have a problem with the windows registry and wouldnt find the correct dependencies, altough they were installed.

on windows gajim itself is a 32bit application, sooo i think we should provide the 32bit dependencies.

but i dont really understand this in regard to python files, cause i can open them, so they are not compiled, i think they get compiled at runtime or not? so every computer would compile them like he needed? so i dont really understand how we could provide x64 or 32, all we can do is provide the .py files.

**Comment by kalkin** [comment]
@lovetox 

> ok i will go over that wiki over the next week

Thanks!

> i have to take that back, a windows user cant simply put it in the plugin folder of omemo. cause thats not a standard path where the dependencies are assumed. if you want to provide it there, like you do with the store folder you have to change all the paths in the py files. cause many axolotl files import with kind of absolut paths, like from axolotl.ecc import blbabla but this would not search the module in the plugin directory. so you would have to alter all the files to relative paths.
> 
> but i dont really understand this in regard to python files, cause i can open them, so they are not compiled, i think they get compiled at runtime or not?

I did not mean the python files but the libraries produced by mingw. About 32 vs 64 I need to do more research.

**Comment by lovetox** [comment]
i get this now with the version you put out right now

Traceback (most recent call last):
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\plugin_installer\plugin_installer.py", line 337, in on_plugin_downloaded
    plugins = self.scan_dir_for_plugin(plugin_dir)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\plugin_installer\plugin_installer.py", line 444, in scan_dir_for_plugin
    if not issubclass(module_attr, GajimPlugin) or \
  File "src\common\demandimport.py", line 86, in **getattribute**
  File "src\common\demandimport.py", line 58, in _load
ImportError: No module named NoSessionException

**Comment by lovetox** [comment]
i remember now, axolotl_curve25519 gets compiled with mingw, but there is no mingwx64 download, i think there is only a 32bit version. also in the installation readme of axolotl there is 

`
[build]
compiler=mingw32
`

**Comment by kalkin** [comment]
@lovetox Should work after restarting Gajim.

**Comment by lovetox** [comment]
hm on ubuntu this build works but on windows it stopped. i get

```
Traceback (most recent call last):
  File "src\plugins\pluginmanager.py", line 259, in _execute_all_handlers_of_gui_extension_point
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 233, in connect_ui
    state = self.get_omemo_state(account_name)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 78, in get_omemo_state
    self.omemo_states[account] = OmemoState(account)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\state.py", line 57, in __init__
    self.store = LiteAxolotlStore(db_file)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\store\liteaxolotlstore.py", line 46, in __init__
    self.encryptionStore = EncryptionState(conn)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\store\encryption.py", line 35, in __init__
    """)
OperationalError: near "WITHOUT": syntax error
```

**Comment by kalkin** [comment]
The sqlite version is too old. It does not support the [WITHOUT ROWID](https://www.sqlite.org/withoutrowid.html) statement. Sqlite supports this statement since 2013. Which sqlite version is used and what does provide it?

[Releveant Code](https://github.com/omemo/gajim-omemo/blob/master/store/encryption.py#L30-L35)

**Comment by lovetox** [comment]
its the sqlite.dll Gajim provides in its BIN directory.

i updated it to a recent one and the error is gone.

could you change the code to something that is supported by the 2013 version?

otherwise windows users would have to hope that gajim updates there sqlite version, or update it themself.

it would get more and more of a hurdle to install this on windows.

**Comment by lovetox** [comment]
also do you think we could provide a zip file in the wiki (install for windows) with all the dependencies already provided. so that someone who just wants to install this quick would just have to copy the content of zip into his bin folder.

like in addition to the compiling section, for people who want to do it themself

i would provide this zip file

**Comment by lovetox** [comment]
Back to the Error when i click "Get Device Keys"

i have the XML Console open, but if i hit the button the error pops up, jabber does not send out anything or getting anything at the moment i hit the key

also this is also in the log, the error message is slightly different to befor

here both: the one i get when i click the button

```
Traceback (most recent call last):
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\ui.py", line 51, in on_click
    self.plugin.query_prekey(self.contact)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 246, in query_prekey
    self.fetch_device_bundle_information(state, to_jid, device_id)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 267, in fetch_device_bundle_information
    iq = BundleInformationQuery(jid, device_id)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 92, in __init__
    pubsub = PubsubNode(items)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 51, in __init__
    assert data is Node
AssertionError
```

the one in the log:

```
Traceback (most recent call last):
  File "src\common\ged.py", line 93, in raise_event
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 197, in handle_device_list_update
    self.publish_own_devices_list(state)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 222, in publish_own_devices_list
    iq = DeviceListAnnouncement(devices_list)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 66, in __init__
    publish = PublishNode(NS_DEVICE_LIST, list_node)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 44, in __init__
    assert node_str is not None and data is Node
AssertionError
```

**Comment by kalkin** [comment]
> could you change the code to something that is supported by the 2013 version?

Yes. I created a new issue See #31

> otherwise windows users would have to hope that gajim updates there sqlite version, or update it themse
> Yes we should fix it, but we also should urge Gajim to update the Sqlite version provided
> 
> also do you think we could provide a zip file in the wiki (install for windows) with all the dependencies already provided. so that someone who just wants to install this quick would just have to copy the content of zip into his bin folder

This would be great! I would just add them to the git in own directory `windows/`, because I think you can not upload files in the wiki(?). I will accept a PR, but only if it's reproducible documented somewhere how you build the dependencies

> Back to the Error when i click "Get Device Keys"

It looks to me like two different errors. The first one happens when you try to fetch bundle information for keys, the other one when you publish your own device list. Can you please paste 10-15 lines of log output, before one of the errors happens?

**Comment by lovetox** [comment]
did send you an email with the log, hope it helps

i started the application with the --verbose flag i think thats the most you can catch

**Comment by kalkin** [comment]
@lovetox I looked through the log, but I have not found anything suspicious. I would ask you to try the current HEAD (it also fixes #31).

When using the current HEAD add a `-l omemo=DEBUG` as a parameter to gajim (not only `-l gajim_plugins.omemo`, this is because omemo is now it's own package [omemo/python-omemo](/omemo/python-omemo) . 

I'm sorry for the inconvience. We will pinpoint the issue, even if it takes some time. I really grateful for the efforts you are undertaking :+1:

**Comment by lovetox** [comment]
with the current HEAD nothing changed

i get these 2 errors in the log, but they were there before

```
Logger gajim.omemo level set to 10
14.01.2016 17:06:56 (E) gajim.c.ged: Error while running an even handler: <bound method OmemoPlugin.signed_in of <omemo.OmemoPlugin object at 0x03EF8AD0>>
14.01.2016 17:07:00 (E) gajim.c.ged: Error while running an even handler: <bound method OmemoPlugin.signed_in of <omemo.OmemoPlugin object at 0x03EF8AD0>>
```

still same error message when i click on the button for device keys.

maybe you could build in some error catching code and i try it out. cause the error message doesnt seem very informativ.

thanks for taking the work, i use this plugin everyday with my girlfriend ( with ubuntu ) .

**Comment by kalkin** [comment]
@lovetox I think i found the issue. I think the device_id and the device_list given to BundleInformationQuery and DeviceListAnnouncement are empty/invalid. I added some more asserts, so we can see if something goes wrong there. Please try the current HEAD.

**Comment by lovetox** [comment]
nothing changed, also no new errors in the log with -l omemo=DEBUG

**Comment by lovetox** [comment]
i printed out the variable to the log which causes the assert to fail

looks like this: 

```
27.01.2016 20:42:12 (W) gajim.plugin_system.omemo: <items node="eu.siacs.conversations.axolotl.bundles:679408871" />
```

**Comment by yann-l** [comment]
same behavior, same traceback here with plugin from gajim FTP repository.

**Comment by yann-l** [comment]
I fixed the tracebacks by changing "data is Node" by "isinstance(data, Node)" in xmpp.py in 2 places.

I was able to exchange an encrypted message, but got other tracebacks, probably not related to this ticket:

**Comment by lepasserby** [comment]
Pardon me, but is there a definitive guide here to "making this plugin work on Windows version of Gajim" ? (I did try to follow the wiki, but I'm not getting any success) 
@yann-l could you go into more details as to how to got to the "at least we can exchange messages" stage?

**Comment by arebokert** [comment]
I tried the guide provided by @lovetox but it does not work. I followed it thoroughly but the plugin won't activate, and the config button in plugins shows an empty box when I click it.

Could anyone provide the compiled files to see if that works?

**Comment by lovetox** [comment]
here: http://www45.zippyshare.com/v/C4Yq5X6W/file.html

it is enough if you copy all the files into
C:\Program Files (x86)\Gajim\bin

please report if you encounter the same error as we after that

though it could be that i went wrong somewhere in compiling the dependencies and that the error comes from that.

so if someone is able to do this himself it would be better.

**Comment by arebokert** [comment]
@lovetox Thank you. I tried the Get Device Keys 1 and got the same trace.

> Traceback (most recent call last):
>   File "C:\Users####\AppData\Roaming\Gajim\Plugins\omemo\ui.py", line 50, in on_click
>     self.plugin.query_prekey(self.contact)
>   File "src\plugins\helpers.py", line 107, in wrapper
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo__init__.py", line 284, in query_prekey
>     device_id)
>   File "src\plugins\helpers.py", line 107, in wrapper
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo__init__.py", line 309, in fetch_device_bundle_information
>     iq = BundleInformationQuery(jid, device_id)
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 95, in **init**
>     pubsub = PubsubNode(items)
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 51, in **init**
>     assert data is Node
> AssertionError

**Comment by lovetox** [comment]
yes welcome to the club

maybe @kalkin has time to build in some more error catching so we can pin this down :)

**Comment by kalkin** [comment]
@arebokert @lovetox Can you add to the assert and try again:

``` python
assert data is Node, "PubsubNode received ⇒ %s" % str(data)
```

**Comment by arebokert** [comment]
@kalkin Adding that string gave me this.

> Traceback (most recent call last):
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo\ui.py", line 50, in on_click
>     self.plugin.query_prekey(self.contact)
>   File "src\plugins\helpers.py", line 107, in wrapper
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo__init__.py", line 284, in query_prekey
>     device_id)
>   File "src\plugins\helpers.py", line 107, in wrapper
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo__init__.py", line 309, in fetch_device_bundle_information
>     iq = BundleInformationQuery(jid, device_id)
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 95, in **init**
>     pubsub = PubsubNode(items)
>   File "C:\Users\####\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 51, in **init**
>     assert data is Node, "PubsubNode received ⇒ %s" % str(data)
> AssertionError: PubsubNode received ⇒ <items node="eu.siacs.conversations.axolotl.bundles:1178132921" />

**Comment by lovetox** [comment]
for me

```
Traceback (most recent call last):
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\ui.py", line 50, in on_click
    self.plugin.query_prekey(self.contact)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 284, in query_prekey
    device_id)
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\__init__.py", line 309, in fetch_device_bundle_information
    iq = BundleInformationQuery(jid, device_id)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 95, in __init__
    pubsub = PubsubNode(items)
  File "C:\Users\Philipp\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 51, in __init__
    assert data is Node, "PubsubNode received ⇒ %s" % str(data)
AssertionError: PubsubNode received ⇒ <items node="eu.siacs.conversations.axolotl.bundles:679408871" />
```

for me it works under linux with the same account, i use jabber.at and conversations at the other end

**Comment by kalkin** [comment]
On 04/12/2016 01:59 PM, Erik wrote:

> @kalkin https://github.com/kalkin Adding that string gave me this.
> 
> ```
> assert data is Node, "PubsubNode received ⇒ %s" % str(data)
> AssertionError: PubsubNode received ⇒
> ```

Looks like you receiving no data from server. Did OMEMO work for you in
Linux with the same account? (Just to rule out, that the server is
sending weird stuff).

kalkin-

**Comment by arebokert** [comment]
@kalkin I think I forgot to escape one of the arrows in my comment, now it shows the whole string as follows.

> AssertionError: PubsubNode received ⇒ <items node="eu.siacs.conversations.axolotl.bundles:1178132921" />

**Comment by kalkin** [comment]
@arebokert @lovetox Can you guys just remove this assert line and try it? Because the string looks right, but for some reason, it not of the class Node which it should be.

**Comment by lovetox** [comment]
lol seems to work now, i can send encrypted messages at least, waiting for my gf to reply :)

i will test this in the evening more and get back to you
more interesting is why this line of code works under linux and not in windows

**Comment by arebokert** [comment]
I removed the assertion and my contact on conversations is saying that omemo is indeed working. I'm using prosody as a server.

**Comment by yann-l** [comment]
Please see https://github.com/omemo/gajim-omemo/issues/12#issuecomment-192982330

I proposed a way to fix this assert line

**Comment by lovetox** [comment]
maybe this has to do something with google protobuf?
does that not have to do something with transforming data back to objects/classes after transfer?! maybe something goes wrong there, maybe we use another version on windows ect

**Comment by kalkin** [comment]
On 04/12/2016 02:13 PM, lovetox wrote:

> lol seems to work now, i can send encrypted messages at least, waiting
> for my gf to reply :)

May be something is different in the simplexml Windows version? Or may
be I just fucked up somewhere. ☹

**Comment by kalkin** [comment]
On 04/12/2016 02:13 PM, lovetox wrote:

> lol seems to work now, i can send encrypted messages at least, waiting
> for my gf to reply :)

May be something is different in the simplexml Windows version? Or may
be I just fucked up somewhere. ☺

**Comment by arebokert** [comment]
@yann-l I tried changing the assertion line to the one you suggested before I tried anything else but still got a traceback error.

**Comment by kalkin** [comment]
@yann-l Indeed, stupid stupid mistake on my side.

**Comment by yann-l** [comment]
@arebokert me too, but not on this line anymore

**Comment by kalkin** [comment]
Can some one post the new traceback?

**Comment by lovetox** [comment]
i dont have any, with deletion of the assert line everything works until now

**Comment by yann-l** [comment]
I had those tracebackes when I tested:http://conference.gajim.org:5280/muc_log/gajim/2016-03-06/#21:16:42

**Comment by kalkin** [comment]
@yann-l The url you provided does not work for me. The server keeps the connection open but does not send any data

**Comment by yann-l** [comment]
and this one ? http://conference.gajim.org:5281/muc_log/gajim/2016-03-06/#21:16:42

**Comment by iNPUTmice** [comment]
```
03/06/2016 21:21:58 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f2bccc37050>>
Traceback (most recent call last):
File "/home/asterix/gajim_0.16/src/common/ged.py", line 93, in raise_event
if handler(*args, **kwargs):
File "/home/asterix/gajim_0.16/src/plugins/helpers.py", line 107, in wrapper
result = f(*args, **kwargs)
File "/home/asterix/.local/share/gajim/plugins/omemo/__init__.py", line 136, in message_received
plaintext = state.decrypt_msg(msg_dict)
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/state.py", line 160, in decrypt_msg
encrypted_key)
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/state.py", line 307, in handlePreKeyWhisperMessage
key = sessionCipher.decryptPkmsg(preKeyWhisperMessage)
File "/usr/local/lib/python2.7/dist-packages/axolotl/sessioncipher.py", line 91, in decryptPkmsg
unsignedPreKeyId = self.sessionBuilder.process(sessionRecord, ciphertext)
File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 47, in process
self.identityKeyStore.saveIdentity(self.recipientId, theirIdentityKey)
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/liteaxolotlstore.py", line 73, in saveIdentity
self.identityKeyStore.saveIdentity(recepientId, identityKey)
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/liteidentitykeystore.py", line 72, in saveIdentity
c.execute(q, (recipientId, identityKey.getPublicKey().serialize()))
IntegrityError: UNIQUE constraint failed: identities.recipient_id
```

and

```
03/06/2016 21:15:37 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.handle_iq_received of <omemo.OmemoPlugin object at 0x7fdce4f61050>>
Traceback (most recent call last):
File "/home/asterix/gajim_0.16/src/common/ged.py", line 93, in raise_event
if handler(*args, **kwargs):
File "/home/asterix/gajim_0.16/src/plugins/helpers.py", line 107, in wrapper
result = f(*args, **kwargs)
File "/home/asterix/.local/share/gajim/plugins/omemo/__init__.py", line 267, in handle_iq_received
iq_ids_to_callbacks[id_](event.stanza)
File "/home/asterix/.local/share/gajim/plugins/omemo/__init__.py", line 314, in <lambda>
device_id)
File "/home/asterix/gajim_0.16/src/plugins/helpers.py", line 107, in wrapper
result = f(*args, **kwargs)
File "/home/asterix/.local/share/gajim/plugins/omemo/__init__.py", line 357, in session_from_prekey_bundle
if state.build_session(recipient_id, device_id, bundle_dict):
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/state.py", line 77, in build_session
sessionBuilder.processPreKeyBundle(prekey_bundle)
File "/usr/local/lib/python2.7/dist-packages/axolotl/sessionbuilder.py", line 173, in processPreKeyBundle
self.sessionStore.storeSession(self.recipientId, self.deviceId, sessionRecord)
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/liteaxolotlstore.py", line 102, in storeSession
self.sessionStore.storeSession(recepientId, deviceId, sessionRecord)
File "/home/asterix/.local/share/gajim/plugins/omemo/omemo/litesessionstore.py", line 61, in storeSession
c.execute(q, (recipientId, deviceId, sessionRecord.serialize()))
IntegrityError: UNIQUE constraint failed: sessions.recipient_id
```

this looks like your database is corrupt maybe from previous attempts

**Comment by iNPUTmice** [comment]
@yann-l for the time I would recommend just deleting the database and start over. If it happens again please try to make it reproducible.

**Comment by kalkin** [comment]
@yann-l the second link works

**Comment by kalkin** [comment]
So Gajim-OMEMO has now Windows support?

**Comment by kalkin** [comment]
@yann-l It would be great if you can add `python-axolotl` and other dependencies to default Gajim windows distribution.

**Comment by yann-l** [comment]
I'll re-test when I have time and will ship python-axolotl with installer if it works. But I think a small tuto in the wiki could help. I have no idea what the buttons are for and what they mean for example.

**Comment by lovetox** [comment]
also `google protobuf` and this file is needed `pkg_resources.py`

**Comment by shr000ms** [comment]
I testet it and after adding the Fix assertion bug I was able to send and receive omemo encrypted messages with conversations. 
But when I restarted gajim I got the following error message. And the omemo settings inside the chat window are gone. 
I can receive omemo encrypted messages from conversations, but when I send a message to conversations I can only see myself typing. I don't receive the message.

Here are my errors after I restarted Gajim:

> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 314, in 'calling callback function'
>   File "c:\python27\lib\site-packages\pybonjour.py", line 1452, in _callback
>     call is using information previously saved (e.g. in a
>   File "src\common\zeroconf\zeroconf_bonjour.py", line 139, in service_resolved_callback
>   File "src\common\zeroconf\connection_zeroconf.py", line 154, in _on_new_service
>   File "src\common\zeroconf\roster_zeroconf.py", line 68, in setItem
> IndexError: tuple index out of range
> 
> Traceback (most recent call last):
>   File "src\common\zeroconf\connection_zeroconf.py", line 140, in _on_resolve_timeout
>   File "src\common\zeroconf\roster_zeroconf.py", line 48, in getDiffs
>   File "src\common\zeroconf\roster_zeroconf.py", line 32, in update_roster
>   File "src\common\zeroconf\roster_zeroconf.py", line 68, in setItem
> IndexError: tuple index out of range
> 
> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 314, in 'calling callback function'
>   File "c:\python27\lib\site-packages\pybonjour.py", line 1452, in _callback
>     call is using information previously saved (e.g. in a
>   File "src\common\zeroconf\zeroconf_bonjour.py", line 174, in service_resolved_all_callback
> NameError: global name 'C_TXT' is not defined

Update:
I disabled the omemo plugin and restarted Gajim and enabled it again and now it works even after restarting gadjim. But i still get the error messages when I start gajim. I tried on a second laptop and got the same errors.

I also get an error when I close the chat windows after I send a message. I can receive the message but the sender gets this error:

> Traceback (most recent call last):
>   File "c:\python27\lib\site-packages\nbxmpp\dispatcher_nb.py", line 497, in dispatch
>     handler['func'](session, stanza)
>   File "src\common\connection_handlers.py", line 1832, in _messageCB
>   File "src\common\nec.py", line 76, in push_incoming_event
>   File "src\common\nec.py", line 98, in _generate_events_based_on_incoming_event
>   File "src\common\connection_handlers_events.py", line 1248, in generate
>   File "src\session.py", line 481, in handle_negotiation
> AttributeError: 'NoneType' object has no attribute 'parent_win'

**Comment by kalkin** [comment]
@shr000ms Try gajim issue tracker looks to me like a gajim issue if it persist even if the OMEMO plugin is disabled

**Comment by Cose-3D** [comment]
I have windows 7 and after this error message nothing happens apparently

```
Traceback (most recent call last):
  File "src\dialogs.py", line 1680, in on_response_yes
  File "src\plugins\gui.py", line 270, in on_yes
  File "src\plugins\pluginmanager.py", line 564, in install_from_zip
  File "src\plugins\helpers.py", line 114, in wrapper
  File "src\plugins\pluginmanager.py", line 128, in add_plugin
  File "src\plugins\helpers.py", line 107, in wrapper
  File "src\plugins\plugin.py", line 161, in __init__
  File "src\plugins\helpers.py", line 107, in wrapper
  File "C:\Users\"myusername"\AppData\Roaming\Gajim\Plugins\plugin_installer/plugin_installer.py", line 64, in init
    self.config_dialog = PluginInstallerPluginConfigDialog(self)
TypeError: 'NoneType' object is not callable
```

**Comment by lovetox** [comment]
i guess you downloaded the plugin here? and not over the plugin ftp function in gajim?
i dont think that has something to do with omemo
try to see if there is an update for the "plugin installer" component under the Plugins section in Gajim.

@kalkin could you push a new version to the gajim ftp, with plugin working now on windows is i think a great enough change that its worth a new version.

**Comment by Cose-3D** [comment]
@lovetox yep

**Comment by lovetox** [comment]
i would download all updates for plugins which are available especially the plugin installer, then download omemo from within gajim, then download the version here, and replace the files.

beware the folder tree is different if you download here, so dont just copy paste the omemo folder

**Comment by kalkin** [comment]
@lovetox 
Does the current HEAD work for you? After @iNPUTmice fiddling with it, it's partly broken for me, but I can't pinpoint if it's  Gajim or OMEMO, because  I currently don't have the time or desire to debug this peace of ⚛☠☆ called Gajim. 

Also deploying an update to FTP means every one will need to re-enable the plugin after update, because Gajim will go haywire if you are reloading a plugin with external dependencies like _axolotl_. If this is fixed in Gajim 0.16 HEAD i will push out a new update.

**Comment by lovetox** [comment]
it does work for me on windows and on ubuntu

**Comment by kalkin** [comment]
@lovetox Ok, I will push out a new version in few days. Thank you and other for your patience and help.

**Comment by Cose-3D** [comment]
@lovetox I cannot click to enable the omemo plugin, it's grey. Maybe I don't have python-axolotl? How the heck do I install it. It's really trublesome for a windows user.

**Comment by therob84** [comment]
Nice to see you working on this!
I would also love to have a short HowTo for getting OMEMO running under Windows without the need to compile myself some stuff...
Thanks a lot!

**Comment by lovetox** [comment]
here are the dependencies: http://www45.zippyshare.com/v/C4Yq5X6W/file.html

it is enough if you copy all the files into
C:\Program Files (x86)\Gajim\bin

download the plugin first over the plugin setting in gajim

then download this version here, and replace the files in
C:\Users\xxxx\AppData\Roaming\Gajim\Plugins\omemo

the file tree in the zip (downloaded source code from here) is a bit different tough
in your plugins/omemo folder you have another "omemo" folder you have to overwrite it with the contents in:
`gajim-omemo-master\lib\python-omemo\src\omemo`

everything else should be the same as in the downloaded zip from here.

or you wait until kalkin pushes a new version.

you can start now gajim, go to plugins and activate omemo
the omemo button is only visible if your contact can also use omemo.
this can take a view seconds at the first start to check.

press "Get Device Key" once, and all should be working from that on

**Comment by Cose-3D** [comment]
@lovetox After installing the dependancies I finally had the OMEMO buttons (OMEMO didn't work though), then I replaced the files in the appdata folder as you told me but after that change the buttons disappeared...

**Comment by podkilla** [comment]
@lovetox thanks for the howto but sadly it does not work for me this way. no idea why but in gajim it is still all the same - plugin is installed but i cannot activate it.
i also tried to compile it by myself installed gcc from minigw but compilation process stops with an error. i tried both 32bit and 64bit versions of python.
i am on win10 enterprise atm.
i will just wait for further information in this thread and try again later.

**Comment by lovetox** [comment]
@edo44 buttons dissapearing points to a not working plugin / error in loading the plugin.
i decribed it misleading, you have to overwrite the `plugins\omemo\omemo` with `gajim-omemo-master\lib\python-omemo\src\omemo`

and additionally overwrite the other files in `plugins\omemo` (xmpp.py ..)

tell me how it went

**Comment by lovetox** [comment]
@kalkin this symlink you set to the omemo library, is only working with linux, this makes it harder for windows users to download the github version and using it, cause they have to copy the omemo library to the right place.

it this really necessary? can this be solved another way?

**Comment by Cose-3D** [comment]
@lovetox I removed OMEMO, reinstalled from the plugin installer, replaced the python files of that folder. It still doesn't work for some reason. (I can't see the buttons)

**Comment by yann-l** [comment]
I already built a windows installer with the omemo libraries included. Just waiting some feedback before I publish it. If some of you want to test it's here:
https://gajim.org/downloads/snap/win/gajim_0.16.5_axolotl.exe

**Comment by arebokert** [comment]
@yann-l I uninstalled gajim and downloaded the version you provided. It seems to work fine with omemo without any external dependencies needed. One thing I got though was this error on first start. It went away after I started it the second time:

https://codebo.xyz/24-04-16-1g.png

**Comment by yann-l** [comment]
yes ... some of you have this problem. Maybe an intl.dll file already installed on the machine and used by the installer, and a different on used by Gajim, but as Gajim is launched by the installer, that may be the problem. I couldn't reproduce and never find a good solution to that.

**Comment by Cose-3D** [comment]
I also installed it and now I can see the buttons (!!) with no errors. But I still can't make it  work with Conversations somehow... And I'm using Openfire as XMPP server, which supports PEP: https://www.igniterealtime.org/builds/openfire/docs/latest/documentation/protocol-support.html

**Comment by kalkin** [comment]
@lovetox We can remove it. [python-omemo](https://github.com/omemo/python-omemo) will be killed in favor of the [matrix olm](https://matrix.org/git/olm/tree/) implementation (I'm just waiting that Conversations get's support for it.), so there is no need in a standalone python-omemo library and for now we can go back to just dropping the code in to gajim-omemo directly.

**Comment by kalkin** [comment]
About releasing a new version of gajim-omemo: There are some issues with the latest protobuf version which I want solve, before releasing.

**Comment by kalkin** [comment]
@lovetox Congratulations you are a team member now and you have push access. Use your powers wisely and only for good :smile:

**Comment by lovetox** [comment]
thanks @yann-l , @kalkin 

@edo44 
create an account at jabber.at, and try it. to rule out a server issue

**Comment by Cose-3D** [comment]
@lovetox I made 2 accounts at jabber.at but the result is the same. So the problem is Conversation or Gajim+omemo (so Gajim I suppose).

**Comment by lovetox** [comment]
did you press the "Get Device Key" Button?

whats exactly the problem?
are the message not coming through?
are the messages coming through if you uncheck the omemo checkbox in the chat window?

**Comment by Cose-3D** [comment]
@lovetox Sorry now for some reason I don't have the buttons anymore so I cannot make you a screenshot... Whenever I pressed "Get the Device Key" or Clear Keys I always had pyhon errors by the way.

And whenever I enabled OMEMO I couldn't send anything.

**Comment by Cose-3D** [comment]
Here the error I get when I click "Get device Key" :

> Traceback (most recent call last):
>   File "C:\Users\edo44\AppData\Roaming\Gajim\Plugins\omemo\ui.py", line 50, in on_click
>     self.plugin.query_prekey(self.contact)
>   File "src\plugins\helpers.py", line 107, in wrapper
>   File "C:\Users\edo44\AppData\Roaming\Gajim\Plugins\omemo__init__.py", line 284, in query_prekey
>     device_id)
>   File "src\plugins\helpers.py", line 107, in wrapper
>   File "C:\Users\edo44\AppData\Roaming\Gajim\Plugins\omemo__init__.py", line 309, in fetch_device_bundle_information
>     iq = BundleInformationQuery(jid, device_id)
>   File "C:\Users\edo44\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 95, in **init**
>     pubsub = PubsubNode(items)
>   File "C:\Users\edo44\AppData\Roaming\Gajim\Plugins\omemo\xmpp.py", line 51, in **init**
>     assert data is Node
> AssertionError

And sorry if I am off topic but I don't know where to  ask. I tried to install gajim in my ubuntu 16.4 machine, but after installing plugins and dependancies the program crashes at startup, here's the error:

`gajim
Traceback (most recent call last):
  File "gajim.py", line 533, in <module>
    interface.run()
  File "/usr/share/gajim/src/gui_interface.py", line 2733, in run
    gajim.plugin_manager = plugins.PluginManager()
  File "/usr/share/gajim/src/plugins/helpers.py", line 129, in __call__
    cls.instance=super(Singleton, cls).__call__(*args,**kw)
  File "/usr/share/gajim/src/plugins/pluginmanager.py", line 104, in __init__
    pc = PluginManager.scan_dir_for_plugins(path)
  File "/usr/share/gajim/src/plugins/helpers.py", line 114, in wrapper
    result = f(*args, **kwargs)
  File "/usr/share/gajim/src/plugins/pluginmanager.py", line 454, in scan_dir_for_plugins
    module = __import__(module_name)
  File "/usr/share/gajim/src/common/demandimport.py", line 95, in _demandimport
    return _import(name, globals, locals, fromlist, level)
  File "/home/Username/.local/share/gajim/plugins/omemo/__init__.py", line 42, in <module>
    from omemo.state import OmemoState
  File "/usr/share/gajim/src/common/demandimport.py", line 114, in _demandimport
    mod = _origimport(name, globals, locals)
  File "/home/Username/.local/share/gajim/plugins/omemo/omemo/state.py", line 29, in <module>
    from axolotl.protocol.prekeywhispermessage import PreKeyWhisperMessage
  File "/usr/share/gajim/src/common/demandimport.py", line 114, in _demandimport
    mod = _origimport(name, globals, locals)
  File "/home/Username/.local/lib/python2.7/site-packages/axolotl/protocol/prekeywhispermessage.py", line 9, in <module>
    from .whispermessage import WhisperMessage
  File "/usr/share/gajim/src/common/demandimport.py", line 112, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/home/Username/.local/lib/python2.7/site-packages/axolotl/protocol/whispermessage.py", line 9, in <module>
    from . import whisperprotos
  File "/usr/share/gajim/src/common/demandimport.py", line 112, in _demandimport
    return _origimport(name, globals, locals, fromlist, level)
  File "/home/Username/.local/lib/python2.7/site-packages/axolotl/protocol/whisperprotos.py", line 21, in <module>
    serialized_pb=_b('\n\x19WhisperTextProtocol.proto\x12\ntextsecure\"b\n\x0eWhisperMessage\x12\x12\n\nratchetKey\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\r\x12\x17\n\x0fpreviousCounter\x18\x03 \x01(\r\x12\x12\n\nciphertext\x18\x04 \x01(\x0c\"\x8f\x01\n\x14PreKeyWhisperMessage\x12\x16\n\x0eregistrationId\x18\x05 \x01(\r\x12\x10\n\x08preKeyId\x18\x01 \x01(\r\x12\x16\n\x0esignedPreKeyId\x18\x06 \x01(\r\x12\x0f\n\x07\x62\x61seKey\x18\x02 \x01(\x0c\x12\x13\n\x0bidentityKey\x18\x03 \x01(\x0c\x12\x0f\n\x07message\x18\x04 \x01(\x0c\"t\n\x12KeyExchangeMessage\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61seKey\x18\x02 \x01(\x0c\x12\x12\n\nratchetKey\x18\x03 \x01(\x0c\x12\x13\n\x0bidentityKey\x18\x04 \x01(\x0c\x12\x18\n\x10\x62\x61seKeySignature\x18\x05 \x01(\x0c\"E\n\x10SenderKeyMessage\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\titeration\x18\x02 \x01(\r\x12\x12\n\nciphertext\x18\x03 \x01(\x0c\"c\n\x1cSenderKeyDistributionMessage\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\titeration\x18\x02 \x01(\r\x12\x10\n\x08\x63hainKey\x18\x03 \x01(\x0c\x12\x12\n\nsigningKey\x18\x04 \x01(\x0c\x42\x37\n&org.whispersystems.libaxolotl.protocolB\rWhisperProtos')
  File "/home/Username/.local/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 828, in __init__
    _message.default_pool.AddSerializedFile(self.serialized_pb)
AttributeError: 'module' object has no attribute 'default_pool'`

I have everything updated.

**Comment by kalkin** [comment]
@edo44 You are using the plugin installed from PluginManager, right? It looks to me like a bug which @iNPUTmice solved in HEAD. Can you please tryout the HEAD?

**Comment by dreamflasher** [comment]
I'm getting the same error as @edo44 with https://gajim.org/downloads/snap/win/gajim_0.16.5_axolotl.exe which was provided by @yann-l. Windows 10 x64.
@kalkin How can I tryout HEAD without building under windows? (The problem is that curve doesn't build on py2.7)

**Comment by kalkin** [comment]
On 04/26/2016 03:07 PM, Marcel Ackermann wrote:

> I'm getting the same error as @edo44 https://github.com/edo44 with
> https://gajim.org/downloads/snap/win/gajim_0.16.5_axolotl.exe which was
> provided by @yann-l https://github.com/yann-l. Windows 10 x64.
> @kalkin https://github.com/kalkin How can I tryout HEAD without
> building under windows? (The problem is that curve doesn't build on py2.7)

Just replace the omemo plugin directory installed by the plugin manager,
with the omemo directory from this zip:
https://github.com/omemo/gajim-omemo/archive/0.5-rc1.zip

**Comment by dreamflasher** [comment]
now the generate keys buttons are gone again ^^ This is quite utterly broken...

**Comment by kalkin** [comment]
On 04/26/2016 03:23 PM, Marcel Ackermann wrote:

> now the generate keys buttons are gone again ^^ This is quite utterly
> broken...

There is no "Generate Key" button. Is the OMEMO Plugin listed in the
plugin manager and is it enable?

**Comment by dreamflasher** [comment]
Yes it is. Oh no generate key button anymore? How can I compare fingerprints or see that encryption is enabled?

**Comment by kalkin** [comment]
On 04/26/2016 03:38 PM, Marcel Ackermann wrote:

> Yes it is. Oh no generate key button anymore?

There were never a generate key button, to begin with :)

> How can I compare  fingerprints or see that encryption is enabled?

By implementing this feature :grin:

**Comment by dreamflasher** [comment]
Sorry my fail. I meant "Get device Key" all the time. This button is now gone. Should it be there?

**Comment by kalkin** [comment]
On 04/26/2016 03:44 PM, Marcel Ackermann wrote:

> Sorry my fail. I meant "Get device Key" all the time. This button is now
> gone. Should it be there?

Only if you are missing Device Keys for starting an encrypted
conversation. You should see the OMEMO checkbox in your conversation window.

**Comment by dreamflasher** [comment]
There is no OMEMO checkbox.

**Comment by kalkin** [comment]
On 04/26/2016 03:51 PM, Marcel Ackermann wrote:

> There is no OMEMO checkbox.

Does your chat partners client support OMEMO? It's only showed if he
supports it.

**Comment by dreamflasher** [comment]
Yes. (and it has been showing before replacing with the latest version)

**Comment by Cose-3D** [comment]
@kalkin replacing the omemo folder doesn't allow me  to even enable the OMEMO plugin anymore.

**Comment by dreamflasher** [comment]
ha, the symlink doesn't work under windows. Solution: `lib/python-omemo/src/omemo` needs to be copied in `Gajim\Plugins\omemo\omemo` -- now there is the OMEMO checkbox and the "Get device Key" works! Thank you!

**Comment by kalkin** [comment]
On 04/26/2016 04:08 PM, Marcel Ackermann wrote:

> ha, the symlink doesn't work under windows. Solution:
> |lib/python-omemo/src/omemo| needs to be copied in
> |Gajim\Plugins\omemo\omemo|

Yes I completely forgot about this issue on windows. Will fix that
before release 0.5. Thank you.

**Comment by lovetox** [comment]
@edo44 try this, exchange the `omemo` folder with this folder in the zip, in your plugins directory.

for windows:
http://www10.zippyshare.com/v/buJ3LyTU/file.html

**Comment by Cose-3D** [comment]
@lovetox This works! Finally!

Now sending images via OMEMO has issues, apparently Gajim cannot decode the recieved file, also it doesn't encrypt the uploaded file, while Conversations does both things without any problem even via OTR.

**Comment by lovetox** [comment]
@edo44 picture decryption works partly, there is a plugin which is called "image preview" download it with gajim. in the settings activate to decrypt everything under 10MB

if you get a link it needs about a minute, until the link is decrypted and you can see it in the chat.

encrypted upload is at the moment not supported by the http-upload plugin of gajim

**Comment by Cose-3D** [comment]
@lovetox But "Image preview" does not allow to download the image, it only shows the preview.

**Comment by lovetox** [comment]
yes, that is correct.

**Comment by iNPUTmice** [comment]
@edo44 to download and decrypt images (or other files for that matter) have a look at https://github.com/iNPUTmice/ImageDownloader

**Comment by user7488** [comment]
Just checking, following [Compiling dependencies for Windows](https://github.com/kalkin/gajim-omemo/wiki/Compiling-dependencies-for-Windows) is still the way to go?

**Comment by tristan-k** [comment]
@pedro7 I dont think so, but it's very confusing with all the comments in this issue. I recently installed the plugin on Windows 10 with the setup files from https://gajim.org/downloads/snap/win/gajim_0.16.5_axolotl.exe and it works. 

> I already built a windows installer with the omemo libraries included. Just waiting some feedback before I publish it. If some of you want to test it's here:
> https://gajim.org/downloads/snap/win/gajim_0.16.5_axolotl.exe

**Comment by lovetox** [comment]
this problem will be gone as soon as gajim releases 0.16.6, dependencies will be included then

for now use the download link tristan-k provided for gajim. and download the plugin through gajim, should be working without further hacks.

**Comment by lovetox** [comment]
i wrote a Wiki on Installing on Windows

https://github.com/omemo/gajim-omemo/wiki/Installing-and-Using-on-Windows
