### ISSUE TITLE
[UI] Clearly show which message is encrypted (and how)

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#15]
Right now, it can happen that even though the "OMEMO" box is ticked, messages are sent unencrypted. This is kind of visible due to the lack of a shield to the left of the text field, but the trouble is that sometimes, even when the shield is missing, messages _are_ sent OMEMO-encrypted.

When the OMEMO checkbox is set, it should _never_ send an unencrypted message. This is to prevent the user from accidentally disclosing important information across an insecure channel. 

Furthermore, for incoming messages, it should be possible to see whether they were OMEMO encrypted and authenticated - for example, with a little padlock next to the nickname, or so. The same could then also be used for outgoing messages, for further clarity and symmetry.

**Comment by lovetox** [comment]
I can confirm this

Checkbox for OMEMO is ticked, but every Message i send is unencrypted, at least Conversations shows it as unencrypted. Even when the shield is there.

I also dont know how i get Gajim to again send it encrypted... i cant do more than tick the box.

**Comment by kalkin** [comment]
> Right now, it can happen that even though the "OMEMO" box is ticked, messages are sent unencrypted. This is kind of visible due to the lack of a shield to the left of the text field, but the trouble is that sometimes, even when the shield is missing, messages are sent OMEMO-encrypted.

@RalfJung and @lovetox I would be very grateful if you could   verify with the latest gajim (install instruction [here](https://github.com/kalkin/gajim-omemo#gajim)) and run in debug mode like this: `./launch.sh -l gajim.plugin_system.omemo=DEBUG`. Please post in this issue the debug output if this error hapens again.

> Furthermore, for incoming messages, it should be possible to see whether they were OMEMO encrypted and authenticated - for example, with a little padlock next to the nickname, or so. The same could then also be used for outgoing messages, for further clarity and symmetry.

Well this is currently not possible with gajim. This is the reason why any encryption in Gajim echos the greenish state messages in the history. This issue can not be resolved by _this_ project in the near future. It has to be fixed in Gajim. There is an open [bug](https://trac.gajim.org/ticket/8207) in Trac. Generally the current Gajim maintainer will be glad if anyone will submit patches.

**Comment by lovetox** [comment]
hope this is correct, sadly this debug option doesnt seem to catch my send messages from gajim probably because they are not omemo encrypted?

you see only the ones i received but i did send some in between

i anonymized the JIDS but dont really know about the other keys and numbers

```
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo Opening the DB /home/xxx/.local/share/gajim/omemo_jabber.at.db
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo jabber.at → Announcing OMEMO support via PEP
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo jabber.at ⇒ Received OMEMO pep for jid CONVERSATIONSACC@jabber.at
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo Saving devices for CONVERSATIONSACC@jabber.at → [679408871]
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo jabber.at ⇒ Received OMEMO pep for jid GAJIM-ACC@jabber.at
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo jabber.at ⇒ Received own device_list [1263077183, 1419694825, 1098053041]
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo jabber.at → Publishing bundle was successful
2016-01-04 15:28:17 (D) gajim.plugin_system.omemo jabber.at → Device list up to date
2016-01-04 15:29:10 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:29:10 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:29:10 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:29:10 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:29:10 (D) gajim.plugin_system.omemo jabber.at ⇒ Searching device_ids for contact CONVERSATIONSACC@jabber.at
2016-01-04 15:29:10 (D) gajim.plugin_system.omemo jabber.at ⇒ found device_ids [679408871]
2016-01-04 15:29:24 (I) gajim.plugin_system.omemo Clicked True
2016-01-04 15:30:07 (D) gajim.plugin_system.omemo jabber.at ⇒ OMEMO msg received
2016-01-04 15:30:07 (D) gajim.plugin_system.omemo a3NB62Qu8Nb+wyO3m1HruA==

2016-01-04 15:30:07 (D) gajim.plugin_system.omemo vMqmN7cSkR560J1/0eAFjajX

2016-01-04 15:30:07 (D) gajim.plugin_system.omemo Mwjpj4UBEiEFovhfiGysfggwPNvEZZvp3fvxWYTnNE3oJ7cugN3wcwIaIQUDkq+Vxd1v86Y126Df
R17Fn4aeAjnWPmzhqMtyCmCdJCJSMwohBW4CQUk3RUpeyvxiTXumaiWYubDJ8CMwXvs16n9nyNlN
EAUYACIgrdEzhgggf1hE6WNXiBlBtx30KM1p+sMqUscEedCHbLFYZjShJY927yjn6fvDAjD/sgM=

2016-01-04 15:30:07 (D) gajim.plugin_system.omemo Parsed OMEMO message:{'keys': {1098053041: '3\x08\xe9\x8f\x85\x01\x12!\x05\xa2\xf8_\x88l\xac~\x080<\xdb\xc4e\x9b\xe9\xdd\xfb\xf1Y\x84\xe74M\xe8\'\xb7.\x80\xdd\xf0s\x02\x1a!\x05\x03\x92\xaf\x95\xc5\xddo\xf3\xa65\xdb\xa0\xdfG^\xc5\x9f\x86\x9e\x029\xd6>l\xe1\xa8\xcbr\n`\x9d$"R3\n!\x05n\x02AI7EJ^\xca\xfcbM{\xa6j%\x98\xb9\xb0\xc9\xf0#0^\xfb5\xea\x7fg\xc8\xd9M\x10\x05\x18\x00" \xad\xd13\x86\x08 \x7fXD\xe9cW\x88\x19A\xb7\x1d\xf4(\xcdi\xfa\xc3*R\xc7\x04y\xd0\x87l\xb1Xf4\xa1%\x8fv\xef(\xe7\xe9\xfb\xc3\x020\xff\xb2\x03'}, 'iv': 'ksA\xebd.\xf0\xd6\xfe\xc3#\xb7\x9bQ\xeb\xb8', 'payload': '\xbc\xca\xa67\xb7\x12\x91\x1ez\xd0\x9d\x7f\xd1\xe0\x05\x8d\xa8\xd7', 'sid': 679408871}
No handlers could be found for logger "axolotl.sessionbuilder"
2016-01-04 15:30:07 (D) gajim.plugin_system.omemo PreKeyWhisperMessage -> u�m�X~�J����  {
2016-01-04 15:30:07 (D) gajim.plugin_system.omemo Decrypted msg ⇒ Ja
2016-01-04 15:30:07 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:30:07 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:31:18 (D) gajim.plugin_system.omemo jabber.at ⇒ OMEMO msg received
2016-01-04 15:31:18 (D) gajim.plugin_system.omemo IZIKru/tRTUBtRKvcWpgEQ==

2016-01-04 15:31:18 (D) gajim.plugin_system.omemo Q75SncstskHvQJZ9DbFQoCTU

2016-01-04 15:31:18 (D) gajim.plugin_system.omemo Mwjpj4UBEiEFovhfiGysfggwPNvEZZvp3fvxWYTnNE3oJ7cugN3wcwIaIQUDkq+Vxd1v86Y126Df
R17Fn4aeAjnWPmzhqMtyCmCdJCJSMwohBW4CQUk3RUpeyvxiTXumaiWYubDJ8CMwXvs16n9nyNlN
EAYYACIgXxOK1vX4SPIEN0EnLZUj/ca3zLClQOu3uRCk/8ezE94b1R3gertM9ijn6fvDAjD/sgM=

2016-01-04 15:31:18 (D) gajim.plugin_system.omemo Parsed OMEMO message:{'keys': {1098053041: '3\x08\xe9\x8f\x85\x01\x12!\x05\xa2\xf8_\x88l\xac~\x080<\xdb\xc4e\x9b\xe9\xdd\xfb\xf1Y\x84\xe74M\xe8\'\xb7.\x80\xdd\xf0s\x02\x1a!\x05\x03\x92\xaf\x95\xc5\xddo\xf3\xa65\xdb\xa0\xdfG^\xc5\x9f\x86\x9e\x029\xd6>l\xe1\xa8\xcbr\n`\x9d$"R3\n!\x05n\x02AI7EJ^\xca\xfcbM{\xa6j%\x98\xb9\xb0\xc9\xf0#0^\xfb5\xea\x7fg\xc8\xd9M\x10\x06\x18\x00" _\x13\x8a\xd6\xf5\xf8H\xf2\x047A\'-\x95#\xfd\xc6\xb7\xcc\xb0\xa5@\xeb\xb7\xb9\x10\xa4\xff\xc7\xb3\x13\xde\x1b\xd5\x1d\xe0z\xbbL\xf6(\xe7\xe9\xfb\xc3\x020\xff\xb2\x03'}, 'iv': '!\x92\n\xae\xef\xedE5\x01\xb5\x12\xafqj`\x11', 'payload': 'C\xbeR\x9d\xcb-\xb2A\xef@\x96}\r\xb1P\xa0$\xd4', 'sid': 679408871}
2016-01-04 15:31:18 (D) gajim.plugin_system.omemo PreKeyWhisperMessage -> ��J>
                                                                              �����{d�M
2016-01-04 15:31:18 (D) gajim.plugin_system.omemo Decrypted msg ⇒ Ja
2016-01-04 15:31:18 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-04 15:31:18 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
```

**Comment by kalkin** [comment]
Only OMEMO logging is not enough (I should have thought about it, sorry), you need to enable full logging. Start gajim with `./launch.sh -v`

**Comment by enko** [comment]
Hmm, the image plugin can insert images into the message, maybe you can insert a lock image into the message the same way?

**Comment by RalfJung** [comment]
It must be clear though that the image comes from Gajim, not from the remote user... so it should probably appear before the nickname. Also, it'd be even better if the tooltip could provide further information, like which encryption was used.

**Comment by lovetox** [comment]
@kalkin i have now a more detailed log with "-v" flag, can i send it via email to you, its to big for posting and i really am to lazy to anonymize all the personal data in this log.

**Comment by kalkin** [comment]
@lovetox My Email should be visible in my Github profile.

**Comment by kalkin** [comment]
This should be fixed by ce63cc8e583dc6099b45d8cb44ee95c9394b6bd2

**Comment by lovetox** [comment]
hm still cant sent encrypted messages.
i uninstalled the plugin from the Gajim menu, then reinstalled it from the pluginmanager, then downloaded the updatet files from here, and replaced the files in the plugin directory.

how can i completely reset the database, maybe there is a problem there?

the reason i say its not encrypted is:
1. my chat partners conversations client shows it as unencrypted
2. i think it should look different in the logs when i send a message? (im not sure about that)
´´´
<message xmlns="jabber:client" to="conversations-client@jabber.at" type="chat" id="40"><body>hi</body><active xmlns="http://jabber.org/protocol/chatstates" /><thread>gLlKOYpMcndtkHPCFiXeYmbggTKxXMXC</thread></message>
```


here the log:

```
_____________

2016-01-08 14:51:25 (D) gajim.c.ged stanza-sent
Args: (<common.connection_handlers_events.StanzaSentEvent object at 0x7fb5441e2990>,)
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.connect_with_chat_control() <entered>
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.update_button_state() <entered>
2016-01-08 14:51:30 (I) gajim.plugin_system Account jabber.at: httpupload is_supported: True
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.update_button_state() <left>
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.connect_with_chat_control() <left>
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.update_button_state() <entered>
2016-01-08 14:51:30 (I) gajim.plugin_system Account jabber.at: httpupload is_supported: True
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.update_button_state() <left>
2016-01-08 14:51:30 (D) nbxmpp.simplexml Preparing to handle incoming XML stream.
2016-01-08 14:51:30 (I) nbxmpp.simplexml STARTTAG.. DEPTH -> 1 , tag -> vCard, attrs -> {u'xmlns': u'vcard-temp'}
2016-01-08 14:51:30 (I) nbxmpp.simplexml DEPTH -> 1 , tag -> vCard
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.update_button_state() <entered>
2016-01-08 14:51:30 (I) gajim.plugin_system Account jabber.at: httpupload is_supported: True
2016-01-08 14:51:30 (D) gajim.plugin_system HttpuploadPlugin.update_button_state() <left>
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.connect_ui() <entered>
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <entered>
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <left>
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at ⇒ Adding OMEMO ui for conversations-client@jabber.at
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <entered>
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <left>
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at ⇒ Missing keys for conversations-client@jabber.at: 0
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <entered>
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <left>
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at → Missing device sessions: []
2016-01-08 14:51:30 (D) gajim.plugin_system.omemo jabber.at ⇒ Missing keys for conversations-client@jabber.at: 0
2016-01-08 14:51:30 (D) gajim.plugin_system OmemoPlugin.connect_ui() <left>
2016-01-08 14:51:30 (D) gajim.c.ged message-outgoing
Args: (<common.connection_handlers_events.MessageOutgoingEvent object at 0x7fb548eb8650>,)
2016-01-08 14:51:30 (I) nbxmpp.transports_nb Plugging fd 17, W:True, R:True
2016-01-08 14:51:30 (D) gajim.c.ged message-sent
Args: (<common.connection_handlers_events.MessageSentEvent object at 0x7fb5441e2410>,)
2016-01-08 14:51:30 (I) nbxmpp.transports_nb pollout called, state == CONNECTED
2016-01-08 14:51:30 (I) nbxmpp.transports_nb Plugging fd 17, W:False, R:True
2016-01-08 14:51:30 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<message xmlns="jabber:client" to="conversations-client@jabber.at" type="chat" id="38"><active xmlns="http://jabber.org/protocol/chatstates" /><thread>gLlKOYpMcndtkHPCFiXeYmbggTKxXMXC</thread></message>
_____________

2016-01-08 14:51:30 (D) gajim.c.ged stanza-sent
Args: (<common.connection_handlers_events.StanzaSentEvent object at 0x7fb5441e2dd0>,)
2016-01-08 14:51:43 (I) gajim.plugin_system.omemo Clicked True
2016-01-08 14:51:43 (D) gajim.plugin_system OmemoPlugin.omemo_enable_for() <entered>
2016-01-08 14:51:43 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <entered>
2016-01-08 14:51:43 (D) gajim.plugin_system OmemoPlugin.get_omemo_state() <left>
2016-01-08 14:51:43 (D) gajim.plugin_system OmemoPlugin.omemo_enable_for() <left>
2016-01-08 14:51:50 (D) gajim.c.ged message-outgoing
Args: (<common.connection_handlers_events.MessageOutgoingEvent object at 0x7fb548eb8650>,)
2016-01-08 14:51:50 (I) nbxmpp.transports_nb Plugging fd 17, W:True, R:True
2016-01-08 14:51:50 (I) nbxmpp.transports_nb Plugging fd 17, W:True, R:True
2016-01-08 14:51:50 (D) gajim.c.ged message-sent
Args: (<common.connection_handlers_events.MessageSentEvent object at 0x7fb5441e27d0>,)
2016-01-08 14:51:50 (I) nbxmpp.transports_nb pollout called, state == CONNECTED
2016-01-08 14:51:50 (I) nbxmpp.transports_nb Plugging fd 17, W:True, R:True
2016-01-08 14:51:50 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<r xmlns="urn:xmpp:sm:2" />
_____________

2016-01-08 14:51:50 (D) gajim.c.ged stanza-sent
Args: (<common.connection_handlers_events.StanzaSentEvent object at 0x7fb548eb8650>,)
2016-01-08 14:51:50 (I) nbxmpp.transports_nb pollout called, state == CONNECTED
2016-01-08 14:51:50 (I) nbxmpp.transports_nb Plugging fd 17, W:False, R:True
2016-01-08 14:51:50 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<message xmlns="jabber:client" to="conversations-client@jabber.at" type="chat" id="39"><composing xmlns="http://jabber.org/protocol/chatstates" /><thread>gLlKOYpMcndtkHPCFiXeYmbggTKxXMXC</thread></message>
_____________

2016-01-08 14:51:50 (D) gajim.c.ged stanza-sent
Args: (<common.connection_handlers_events.StanzaSentEvent object at 0x7fb548eb8650>,)
2016-01-08 14:51:50 (I) nbxmpp.transports_nb pollin called, state == CONNECTED
2016-01-08 14:51:50 (I) nbxmpp.idlequeue read timeout removed for fd 17
2016-01-08 14:51:50 (I) nbxmpp.idlequeue read timeout set for fd 17 on 55 seconds
2016-01-08 14:51:50 (I) nbxmpp.idlequeue read timeout set for fd 17 on 120 seconds with function <bound method NonBlockingTCP.read_timeout2 of <nbxmpp.transports_nb.NonBlockingTCP instance at 0x7fb548f63b48>>
2016-01-08 14:51:50 (I) nbxmpp.client_nb raising event from transport: :::::DATA RECEIVED::::
_____________
<a xmlns='urn:xmpp:sm:2' h='39'/>
_____________

2016-01-08 14:51:50 (D) gajim.c.ged stanza-received
Args: (<common.connection_handlers_events.StanzaReceivedEvent object at 0x7fb548eb8650>,)
2016-01-08 14:51:50 (I) nbxmpp.simplexml STARTTAG.. DEPTH -> 2 , tag -> a, attrs -> {u'h': u'39', u'xmlns': u'urn:xmpp:sm:2'}
2016-01-08 14:51:50 (I) nbxmpp.simplexml DEPTH -> 2 , tag -> a
2016-01-08 14:51:50 (D) nbxmpp.dispatcher_nb Got urn:xmpp:sm:2/a stanza
2016-01-08 14:51:52 (D) gajim.c.ged message-outgoing
Args: (<common.connection_handlers_events.MessageOutgoingEvent object at 0x7fb548eb8650>,)
2016-01-08 14:51:52 (I) nbxmpp.transports_nb Plugging fd 17, W:True, R:True
2016-01-08 14:51:52 (D) gajim.c.ged message-sent
Args: (<common.connection_handlers_events.MessageSentEvent object at 0x7fb5441e2b90>,)
2016-01-08 14:51:52 (I) nbxmpp.transports_nb pollout called, state == CONNECTED
2016-01-08 14:51:52 (I) nbxmpp.transports_nb Plugging fd 17, W:False, R:True
2016-01-08 14:51:52 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<message xmlns="jabber:client" to="conversations-client@jabber.at" type="chat" id="40"><body>hi</body><active xmlns="http://jabber.org/protocol/chatstates" /><thread>gLlKOYpMcndtkHPCFiXeYmbggTKxXMXC</thread></message>
_____________

2016-01-08 14:51:52 (D) gajim.c.ged stanza-sent
Args: (<common.connection_handlers_events.StanzaSentEvent object at 0x7fb54938c810>,)
2016-01-08 14:52:22 (D) gajim.c.ged message-outgoing
Args: (<common.connection_handlers_events.MessageOutgoingEvent object at 0x7fb548f0d5d0>,)
2016-01-08 14:52:22 (I) nbxmpp.transports_nb Plugging fd 17, W:True, R:True
2016-01-08 14:52:22 (D) gajim.c.ged message-sent
Args: (<common.connection_handlers_events.MessageSentEvent object at 0x7fb5441e2a90>,)
2016-01-08 14:52:22 (I) nbxmpp.transports_nb pollout called, state == CONNECTED
2016-01-08 14:52:22 (I) nbxmpp.transports_nb Plugging fd 17, W:False, R:True
2016-01-08 14:52:22 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<message xmlns="jabber:client" to="conversations-client@jabber.at" type="chat" id="41"><inactive xmlns="http://jabber.org/protocol/chatstates" /><thread>gLlKOYpMcndtkHPCFiXeYmbggTKxXMXC</thread></message>
_____________
```
```

**Comment by lovetox** [comment]
i did find out why it didnt work for me.

i had an old version of gajim, ubuntu software center does only provide version 0.16.0
with this version it didnt matter if the checkbox was checked or not the messages were always unencrypted.

with 0.16.5 and your fixes, now it works for me.

**Comment by kalkin** [comment]
@lovetox Great. Thank you for your feedback!
